<a href="https://colab.research.google.com/github/ShirleyRM/Inteligencia-artificial-/blob/main/practica%233.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as algebralineal

a=algebralineal.array([11,22,33])
print(type(a))
print(a)

print(a[1])
print(a[:2])
print(a[1:3])
a[1]=888
print(a)

<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
[ 11 888  33]


In [12]:
import numpy as np
b=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type(b))
print(b)
print(b[1,1])
aux=b [1:,1:] . copy()
print(aux.shape)
print(aux)

print('BEFORE/......')
print(b)
print(aux)

aux[1,1]=1000

print('AFTER/......')
print(b)
print(aux)





(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
[[ 22  33]
 [222 333]]
BEFORE/......
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 333]]
AFTER/......
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[  22   33]
 [ 222 1000]]


In [13]:
c=np.zeros((4,4))
print(c)
print(c.shape)
d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [15]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
g=np.random.random((5,5))
print(g)

[[0.69000339 0.647933   0.99008059 0.35329919 0.39716932]
 [0.42827527 0.71624959 0.85114708 0.55749973 0.82301468]
 [0.72407385 0.963605   0.56188766 0.19851795 0.86034462]
 [0.68063867 0.66078192 0.25918047 0.06586532 0.61105205]
 [0.45111177 0.95034457 0.23931979 0.39353233 0.03039282]]


In [21]:
tmpl=np.random.randint(1,20,(4,4))
print(tmpl)

rows=np.array([0,1,2,0])
cols=np.arange(4)
print(rows)
print(cols)
print(rows.shape)
print(cols.shape)






[[11 16  5 10]
 [13  4 16  3]
 [15 10  9 15]
 [ 7  3  7  7]]
[0 1 2 0]
[0 1 2 3]
(4,)
(4,)


In [22]:
tmpl[rows,cols]=100
print(tmpl)

[[100  16   5 100]
 [ 13 100  16   3]
 [ 15  10 100  15]
 [  7   3   7   7]]


In [26]:
tmpl=np.random.randint(20,50,(6,6))
print(tmpl)

filter=(tmpl>45)
print(filter)
print(tmpl[filter])


[[35 24 34 37 37 32]
 [32 29 49 34 40 46]
 [34 43 24 47 30 37]
 [33 42 28 20 20 22]
 [28 49 33 49 45 49]
 [44 43 41 27 27 38]]
[[False False False False False False]
 [False False  True False False  True]
 [False False False  True False False]
 [False False False False False False]
 [False  True False  True False  True]
 [False False False False False False]]
[49 46 47 49 49 49]


In [30]:
tmpl=np.random.randint(1,100,(10,10))
print(tmpl)

pares=tmpl[tmpl % 2== 0]
print(pares)


[[13 60 55 72  1 43 13 86  7 66]
 [12 17 99 71 58 24 90 71 43 81]
 [31 42 14 35 43 40 91 37  6 74]
 [16 86 26 18 88 85 41 42 62  8]
 [19 49 74 85 97 89 20 26 60 61]
 [54 77  3 46 67 54 38 17 18 18]
 [70 11 26 40 21 65 85 45  1 91]
 [ 1 91 27 77 65 68 82 81  3 69]
 [90 71 97 64 65 30 15 84  6 21]
 [60 95 45 31 38  5 88 77 76 52]]
[60 72 86 66 12 58 24 90 42 14 40  6 74 16 86 26 18 88 42 62  8 74 20 26
 60 54 46 54 38 18 18 70 26 40 68 82 90 64 30 84  6 60 38 88 76 52]


In [32]:
tmp3=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp3.dtype)

float64


In [38]:
x=np.array([[1,2],[11,22]])
y=np.array([[22,33],[44,55]])
print(x)
print(y)
print(np.add[x,y])
print(np.subtract[x,y])
print(np.multiply[x,y])
print(np.divide[x,y])
print(np.sqrt(x))

[[ 1  2]
 [11 22]]
[[22 33]
 [44 55]]


TypeError: 'numpy.ufunc' object is not subscriptable

In [36]:
tmpl=np.random.randint(1,10,(2,5))
print(tmpl)
aux=tmpl.mean()
print(aux)

[[5 9 5 9 2]
 [1 7 5 7 6]]
5.6


In [37]:
print(tmpl.mean(axis=1))
print(tmpl.mean(axis=0))

[6.  5.2]
[3. 8. 5. 8. 4.]
