<a href="https://colab.research.google.com/github/ShirleyRM/Inteligencia-artificial-/blob/main/prueba%20de%20IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

# Crear los arreglos unidimensionales
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Convertir los arreglos en columnas usando reshape
a_vertical = a.reshape(-1, 1)  #a.reshape permite convertir el arreglo a en una fila
b_vertical = b.reshape(-1, 1)

# Mostrar los arreglos
print("Arreglo a vertical:")
print(a_vertical)

print("Arreglo b vertical:")
print(b_vertical)




Arreglo a vertical:
[[1]
 [2]
 [3]
 [4]]
Arreglo b vertical:
[[5]
 [6]
 [7]
 [8]]


In [20]:
import numpy as np

# Crear los arreglos unidimensionales
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Convertir los arreglos en filas usando reshape
a_horizontal = a.reshape(1, -1)
b_horizontal = b.reshape(1, -1)

# Mostrar los arreglos
print("Arreglo a horizontal:")
print(a_horizontal)

print("Arreglo b horizontal:")
print(b_horizontal)


Arreglo a horizontal:
[[1 2 3 4]]
Arreglo b horizontal:
[[5 6 7 8]]


In [21]:
import numpy as np

# Crear la matriz tmp
tmp = np.arange(15)  #crea un arreglo unidimensional con valores del 0 al 14.

# Obtener todos los elementos entre 5 y 10
result = tmp[(tmp >= 5) & (tmp <= 10)]

# Mostrar el resultado
print("Elementos entre 5 y 10:")
print(result)


Elementos entre 5 y 10:
[ 5  6  7  8  9 10]


In [ ]:
import numpy as np
a=np.array([5,7,9,8,6,4,5])
b=np.array([6,3,4,8,9,7,1])
pair_max(a,b)

