<a href="https://colab.research.google.com/github/ShirleyRM/Inteligencia-artificial-/blob/main/tarea%20de%20la%20prueba%20IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importar numpy y ver la versión
import numpy as np
print(np.__version__)


1.25.2


In [2]:
# Crear un array 1D de números del 0 al 9
array_1d = np.arange(10)
print(array_1d)


[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Crear un vector aleatorio de tamaño 10 y reemplazar el valor máximo por 0
vector = np.random.random(10)
print("Vector original:", vector)
vector[vector.argmax()] = 0
print("Vector modificado:", vector)


Vector original: [0.62534231 0.35591012 0.13499008 0.01110527 0.00795219 0.3144834
 0.81398223 0.61434513 0.91331217 0.25879317]
Vector modificado: [0.62534231 0.35591012 0.13499008 0.01110527 0.00795219 0.3144834
 0.81398223 0.61434513 0.         0.25879317]


In [4]:
# Imprimir el número 8 del array dado
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 2])


8


In [5]:
# Imprimir los números [3, 4, 5] del array dado
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])


[3 4 5]


In [6]:
# Imprimir los últimos 4 números del array dado
arr = np.array([1,2,3,4,5,6,7])
print(arr[-4:])


[4 5 6 7]


In [7]:
# Crear un array numpy de 3x3 con todos valores True
array_true = np.ones((3, 3), dtype=bool)
print(array_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# Extraer todos los números impares del array
arr = np.arange(1, 20)
impares = arr[arr % 2 != 0]
print(impares)


[ 1  3  5  7  9 11 13 15 17 19]


In [9]:
# Crear un vector con valores del 10 al 49
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# Invertir un vector (el primer elemento se convierte en el último)
vector = np.arange(10)
vector_invertido = vector[::-1]
print(vector_invertido)


[9 8 7 6 5 4 3 2 1 0]


In [11]:
# Crear un array de 10x10 con valores enteros aleatorios y encontrar los valores mínimo y máximo
array_10x10 = np.random.randint(0, 100, (10, 10))
min_val = array_10x10.min()
max_val = array_10x10.max()
print("Array:\n", array_10x10)
print("Valor mínimo:", min_val)
print("Valor máximo:", max_val)


Array:
 [[34 35 73 83 83 81 20 92 39  7]
 [85  8 12 73 38 91 41 23 70  8]
 [85 22 71 46 12 29 52  0 66 45]
 [32 61 93 41 36 73 33 86 13 27]
 [53 24 44 29 48 96 27 15 33 13]
 [72 65 38 14 85 21 11 81 48 96]
 [73 60 67 69 81 74 96 91  3 69]
 [27 16 59  7 66 21 40 66 38 24]
 [78 71 61 72 30  6 79 55  6 44]
 [15 97 15 51 68 59 82 12 52 46]]
Valor mínimo: 0
Valor máximo: 97


In [12]:
# Crear un array 3x3x3 con valores aleatorios
array_3x3x3 = np.random.random((3, 3, 3))
print(array_3x3x3)


[[[0.24309639 0.38685774 0.98851876]
  [0.56320525 0.72993634 0.24669797]
  [0.12664772 0.26393572 0.28179009]]

 [[0.08568716 0.68755606 0.66720002]
  [0.3603075  0.8631561  0.66711142]
  [0.35567711 0.83340691 0.09568646]]

 [[0.20543711 0.49756675 0.50872634]
  [0.84312729 0.24005974 0.45110248]
  [0.04356041 0.81246168 0.47034632]]]


In [13]:
# Reemplazar todos los números impares en un array con -1
arr = np.arange(10)
arr[arr % 2 != 0] = -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [14]:
# Crear un array de tipo float
array_float = np.array([1, 2, 3], dtype=float)
print(array_float)


[1. 2. 3.]


In [15]:
# Convertir un array 1D a un array 2D con 2 filas
array_1d = np.arange(10)
array_2d = array_1d.reshape(2, -1)
print(array_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
# Encontrar valores comunes entre dos arrays
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
valores_comunes = np.intersect1d(Z1, Z2)
print("Z1:", Z1)
print("Z2:", Z2)
print("Valores comunes:", valores_comunes)


Z1: [3 4 1 8 0 7 2 4 7 8]
Z2: [0 5 4 2 4 0 9 4 6 2]
Valores comunes: [0 2 4]


In [17]:
# Considerar dos arrays aleatorios A y B, verificar si son iguales
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
iguales = np.array_equal(A, B)
print("A:", A)
print("B:", B)
print("Son iguales:", iguales)


A: [0 0 0 1 1]
B: [0 1 1 1 1]
Son iguales: False


In [18]:
# Apilar arrays a y b verticalmente
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
apilados_vert = np.vstack((a, b))
print(apilados_vert)


[[1 2 3]
 [4 5 6]]


In [19]:
# Apilar los arrays a y b horizontalmente
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
apilados_horiz = np.hstack((a, b))
print(apilados_horiz)


[1 2 3 4 5 6]


In [20]:
# Obtener todos los elementos entre 5 y 10 del array tmp
import numpy as np
tmp = np.arange(15)
elementos = tmp[(tmp >= 5) & (tmp <= 10)]
print(elementos)


[ 5  6  7  8  9 10]


In [21]:
# Hacer que una función Python que maneja escalares funcione con arrays numpy
import numpy as np

def maxx(x, y):
    """Obtener el máximo de dos elementos"""
    if x >= y:
        return x
    else:
        return y

maxx_vectorizado = np.vectorize(maxx)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
resultado = maxx_vectorizado(a, b)
print(resultado)


[6 7 9 8 9 7 5]


In [22]:
# Intercambiar las columnas 1 y 2 en el array arr
arr = np.arange(9).reshape(3, 3)
print("Array original:\n", arr)
arr[:, [1, 2]] = arr[:, [2, 1]]
print("Array modificado:\n", arr)


Array original:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Array modificado:
 [[0 2 1]
 [3 5 4]
 [6 8 7]]


In [23]:
# Crear un array 2D de forma 5x3 para contener números decimales aleatorios entre 5 y 10
array_2d = 5 + (10 - 5) * np.random.random((5, 3))
print(array_2d)


[[9.87596029 6.7709377  6.07476351]
 [5.29909441 9.67689857 8.79264983]
 [6.51457678 5.72064053 8.86980045]
 [6.69895119 8.49196631 9.87454283]
 [5.07375158 7.54414528 5.22309466]]
